apiVersion: v1
kind: Service
metadata:
  name: ensemble-storefront
  labels:
    app: ensemble-storefront
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: 5000
    nodePort: {{ .Values.service.nodePort }}
  selector:
    app: ensemble-storefront
